In [132]:
import pandas as pd

#read file from csv
df = pd.read_csv("Merge.csv", parse_dates = ['Datetime'])

#create a new dataframe between 7.00 to 17.00
df_new = df.loc[(df['Datetime'].dt.strftime('%H:%M:%S') >= '07:00:00') & (df['Datetime'].dt.strftime('%H:%M:%S') <= '17:00:00')]

#set Datetime and Resolution as index
df_index = df_new.set_index(['Datetime', 'Resolution'], inplace = True)

#resample the dataframe for 2 hours resolution
df_new = df_new.groupby(level=1).resample('2H', offset = '1H', level = 0).mean()
df_new.ffill(axis = 0)

print(df_new)

                                    Price
Resolution Datetime
10MIN      2021-11-01 07:00:00  70.857500
           2021-11-01 09:00:00  71.566667
           2021-11-01 11:00:00  68.812500
           2021-11-01 13:00:00  63.250000
           2021-11-01 15:00:00  65.589583
...                                   ...
1H         2021-11-30 07:00:00  97.875000
           2021-11-30 09:00:00  98.625000
           2021-11-30 11:00:00  96.362500
           2021-11-30 13:00:00  97.312500
           2021-11-30 15:00:00  94.175000

[706 rows x 1 columns]